package by.mendelev.xmltask.entity;

public enum Country {
    ALGERIA, ANGOLA, AUSTRALIA, AUSTRIA, BOTSWANA, BRAZIL, CANADA, CHINA, COLOMBIA, CONGO,
    DOMINICAN_REPUBLIC, GERMANY, GHANA, GREECE, GUINEA, GULF_STATES, GUYANA, INDIA,
    INDONESIA, JAPAN, KAMPUCHEA, LAOS, LESOTHO, MADAGASCAR, MALI, MOZAMBIQUE,
    MYANMAR, NIGERIA, NORWAY, OCEANIA, PAKISTAN, POLAND, RUSSIA, SIERRA_LEONE,
    SOUTH_AFRICA, SRI_LANKA, SWITZERLAND, TANZANIA, THAILAND, USA, VENEZUELA,
    ZAMBIA, ZIMBABWE
}
